<?php
/**
 *
 * @category    Sitewards
 * @package     Sitewards_CmsTeaser
 * @copyright   Copyright (c) 2013 Sitewards GmbH (http://www.sitewards.com/)
 */
?>
<?php if(isset($sTeaserImgSrc)) : ?>
    <div class="sitewards-teaser">
        <img src="<?php echo $sTeaserImgSrc; ?>"
             alt="<?php echo $sTeaserImgAlt;?>"
             title="<?php echo $sTeaserImgAlt;?>"/>
    </div>
<?php endif; ?>